-- Declarative desired state for PostgreSQL 16 and CockroachDB.
-- Review diffs with declarative-migrations/declarative-postgres-migrate.rs.
-- Never apply destructive output automatically.

CREATE TABLE IF NOT EXISTS happy_wakey_alarms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id TEXT NOT NULL,
  label TEXT NOT NULL,
  local_time TIME NOT NULL,
  time_zone TEXT NOT NULL,
  weekdays JSONB NOT NULL,
  enabled BOOL NOT NULL DEFAULT true,
  sound TEXT NOT NULL,
  volume DECIMAL(4,3) NOT NULL,
  gradual_seconds INT4 NOT NULL DEFAULT 0,
  tags JSONB NOT NULL DEFAULT '[]'::JSONB,
  generation INT8 NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp(),
  CONSTRAINT happy_wakey_alarm_volume CHECK (volume >= 0 AND volume <= 1),
  CONSTRAINT happy_wakey_alarm_generation CHECK (generation >= 0),
  CONSTRAINT happy_wakey_alarm_gradual CHECK (gradual_seconds >= 0 AND gradual_seconds <= 1800)
);

CREATE INDEX IF NOT EXISTS happy_wakey_alarms_owner_enabled
  ON happy_wakey_alarms (owner_id, enabled, updated_at DESC);

CREATE TABLE IF NOT EXISTS happy_wakey_alarm_occurrences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alarm_id UUID NOT NULL REFERENCES happy_wakey_alarms(id) ON DELETE CASCADE,
  owner_id TEXT NOT NULL,
  scheduled_for TIMESTAMPTZ NOT NULL,
  state STRING NOT NULL,
  generation INT8 NOT NULL DEFAULT 0,
  active_transition_id UUID NULL,
  snooze_until TIMESTAMPTZ NULL,
  acknowledged_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp(),
  CONSTRAINT happy_wakey_occurrence_state CHECK (state IN ('scheduled','firing','acknowledged','snoozed','completed','missed','canceled')),
  CONSTRAINT happy_wakey_occurrence_generation CHECK (generation >= 0),
  UNIQUE (alarm_id, scheduled_for)
);

CREATE INDEX IF NOT EXISTS happy_wakey_occurrences_due
  ON happy_wakey_alarm_occurrences (state, scheduled_for);
CREATE INDEX IF NOT EXISTS happy_wakey_occurrences_owner
  ON happy_wakey_alarm_occurrences (owner_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS happy_wakey_transition_receipts (
  transition_id UUID PRIMARY KEY,
  owner_id TEXT NOT NULL,
  occurrence_id UUID NULL REFERENCES happy_wakey_alarm_occurrences(id) ON DELETE CASCADE,
  request_hash TEXT NOT NULL,
  disposition TEXT NOT NULL,
  response JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp(),
  CONSTRAINT happy_wakey_transition_disposition CHECK (disposition IN ('applied','stale','rejected'))
);

CREATE TABLE IF NOT EXISTS happy_wakey_sync_changes (
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  change_id UUID NOT NULL UNIQUE,
  scope TEXT NOT NULL,
  collection TEXT NOT NULL,
  entity_id UUID NOT NULL,
  operation TEXT NOT NULL,
  generation INT8 NOT NULL,
  actor_id TEXT NOT NULL,
  document JSONB NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT happy_wakey_sync_operation CHECK (operation IN ('upsert','delete')),
  CONSTRAINT happy_wakey_sync_generation CHECK (generation >= 0),
  CONSTRAINT happy_wakey_sync_document CHECK ((operation = 'delete' AND document IS NULL) OR (operation = 'upsert' AND document IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS happy_wakey_sync_scope_sequence
  ON happy_wakey_sync_changes (scope, sequence);
